"""Test

Revision ID: 1c2346cbeff5
Revises: 98259209e240
Create Date: 2024-02-27 23:11:46.609869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c2346cbeff5'
down_revision = '98259209e240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.drop_index('idx_users_deleted_at')
        batch_op.drop_constraint('idx_users_login', type_='unique')
        batch_op.drop_column('secondname')
        batch_op.drop_column('school')
        batch_op.drop_column('lastname')
        batch_op.drop_column('id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('school', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('secondname', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('idx_users_login', ['login'])
        batch_op.create_index('idx_users_deleted_at', ['deleted_at'], unique=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('login',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
