"""empty message

Revision ID: 78a5268130e0
Revises: d72788db2890
Create Date: 2024-03-01 16:01:32.165052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a5268130e0'
down_revision = 'd72788db2890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masterclasses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_masterclasses_hash'), ['hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masterclasses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_masterclasses_hash'))
        batch_op.drop_column('hash')

    # ### end Alembic commands ###
