"""Fixes 34

Revision ID: 9ff01b7fcb5c
Revises: e7ee40bec423
Create Date: 2024-02-26 14:54:16.459263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff01b7fcb5c'
down_revision = 'e7ee40bec423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('masterclass_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('masterclass_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
